import author from './author'
import category from './category'
import post from './post'
import product from './product'
import review from './review'
import siteSettings from './siteSettings'
import tag from './tag'
import trendingTopics from './trendingTopics'
import latestArticles from './latestArticles'
import latestAudioArticles from './latestAudioArticles'
import advertisement from './advertisement'
import lifestyles from './lifestyles'
import newsletter from './newsletter'
import seaTravel from './seaTravel'
import videosSection from './videosSection'
import topAuthors from './topAuthors'

export const schemaTypes = [post, author, category, tag, product, review, siteSettings, trendingTopics, latestArticles, latestAudioArticles, advertisement, lifestyles, newsletter, seaTravel, videosSection, topAuthors]
